instruments = [{"instrument_name" : "cyclone_tt_78",
                "midi_port" : "CH345:CH345 MIDI 1",
                "midi_channel" :10,
                "bass_drum_1" : 36,
                "acoustic_snare" : 38,
                "closed_hi_hat" : 42,
                "ride_cymbal_1" : 51,
                "tambourine" : 54,
                "cowbell" : 56,
                "high_bongo" : 60,
                "low_bongo" : 61,
                "open_high_conga" : 63,
                "low_conga" : 64,
                "maracas" : 70,
                "short_guiro" : 73,
                "long_guiro" : 74,
                "claves" : 75
               },
               {"instrument_name" : "nano_synth",
                "midi_port" : "Pico:Pico CircuitPython usb_midi.por",
                "midi_channel" :10,
                "acoustic_bass_drum":35,
                "bass_drum_1" : 36,
                "side_kick" : 37,
                "acoustic_snare" : 38,
                "hand_clap" : 39,
                "electric_snare" : 40,
                "low_flor_tom" : 41,
                "closed_hi_hat" : 42,
                "high_floor_tom" : 43,
                "pedal_hi_hat" : 44,
                "chick" : 44,
                "low_tom" : 45,
                "open_hi_hat" : 46,
                "low_mid_tom" : 47,
                "high_mid_tom" : 48,
                "crash_cymbal_1" : 49,
                "high_tom" : 50,
                "ride_cymbal_1" : 51,
                "chinese_cymbal" : 52,
                "ride_bell" : 53,
                "tambourine" : 54,
                "splash_cymbal" : 55,
                "cowbell" : 56,
                "crash_cymbal_2" : 57,
                "vibraslap" : 58,
                "ride_cymbal_2" : 59,
                "high_bongo" : 60,
                "low_bongo" : 61,
                "mute_high_conga" : 62,
                "open_high_conga" : 63,
                "low_conga" : 64,
                "high_timbale" : 65,
                "low_timbale" : 66,
                "high_agogo" : 67,
                "low_agogo" : 68,
                "cabasa" : 69,
                "maracas" : 70,
                "short_whistle" : 71,
                "long_whistle" : 72,
                "short_guiro" : 73,
                "long_guiro" : 74,
                "claves" : 75,
                "high_wood_block" : 76,
                "low_wood_block" : 77,
                "mute_cuica" : 78,
                "open_cuica" : 79,
                "mute_triangle" : 80,
                "open_triangle" : 81,
                }
              ]
